# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ed Latimore
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Website of Ed Latimore, undefeated heavy-weight boxer, writer, and physicist
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000" # the base hostname & protocol for your site
url: "http://moss-gorilla1.cloudvent.net"
twitter_username: jekyllrb
github_username:  jekyll

gems: [jekyll-paginate]
paginate: 5

# Build settings
markdown: kramdown

permalink: pretty
excerpt_separator: <!--more-->

version: 3.0.3
